//PACKAGE

export const GET_PACKAGE_PROGRESS = "GET_PACKAGE_PROGRESS";
export const GET_PACKAGE_SUCCESS = "GET_PACKAGE_SUCCESS";
export const GET_PACKAGE_ERROR = "GET_PACKAGE_ERROR";

export const POST_PACKAGE_PROGRESS = "POST_PACKAGE_PROGRESS";
export const POST_PACKAGE_SUCCESS = "POST_PACKAGE_SUCCESS";
export const POST_PACKAGE_ERROR = "POST_PACKAGE_ERROR";

export const DELETE_PACKAGE_PROGRESS = "DELETE_PACKAGE_PROGRESS";
export const DELETE_PACKAGE_SUCCESS = "DELETE_PACKAGE_SUCCESS";
export const DELETE_PACKAGE_ERROR = "DELETE_PACKAGE_ERROR";

export const UPDATE_PACKAGE_PROGRESS = "UPDATE_PACKAGE_PROGRESS";
export const UPDATE_PACKAGE_SUCCESS = "UPDATE_PACKAGE_SUCCESS";
export const UPDATE_PACKAGE_ERROR = "UPDATE_PACKAGE_ERROR";
