//BLOG

export const GET_BLOG_PROGRESS = "GET_BLOG_PROGRESS";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_ERROR = "GET_BLOG_ERROR";

export const POST_BLOG_PROGRESS = "POST_BLOG_PROGRESS";
export const POST_BLOG_SUCCESS = "POST_BLOG_SUCCESS";
export const POST_BLOG_ERROR = "POST_BLOG_ERROR";

export const DELETE_BLOG_PROGRESS = "DELETE_BLOG_PROGRESS";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_ERROR = "DELETE_BLOG_ERROR";

export const UPDATE_BLOG_PROGRESS = "UPDATE_BLOG_PROGRESS";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_ERROR = "UPDATE_BLOG_ERROR";
