//ORDER

export const GET_ORDER_PROGRESS = "GET_ORDER_PROGRESS";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";

export const POST_ORDER_PROGRESS = "POST_ORDER_PROGRESS";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_ERROR = "POST_ORDER_ERROR";

export const DELETE_ORDER_PROGRESS = "DELETE_ORDER_PROGRESS";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_ERROR = "DELETE_ORDER_ERROR";

export const UPDATE_ORDER_PROGRESS = "UPDATE_ORDER_PROGRESS";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR";
