//VIDEO

export const GET_VIDEO_PROGRESS = "GET_VIDEO_PROGRESS";
export const GET_VIDEO_SUCCESS = "GET_VIDEO_SUCCESS";
export const GET_VIDEO_ERROR = "GET_VIDEO_ERROR";

export const POST_VIDEO_PROGRESS = "POST_VIDEO_PROGRESS";
export const POST_VIDEO_SUCCESS = "POST_VIDEO_SUCCESS";
export const POST_VIDEO_ERROR = "POST_VIDEO_ERROR";

export const DELETE_VIDEO_PROGRESS = "DELETE_VIDEO_PROGRESS";
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";
export const DELETE_VIDEO_ERROR = "DELETE_VIDEO_ERROR";

export const UPDATE_VIDEO_PROGRESS = "UPDATE_VIDEO_PROGRESS";
export const UPDATE_VIDEO_SUCCESS = "UPDATE_VIDEO_SUCCESS";
export const UPDATE_VIDEO_ERROR = "UPDATE_VIDEO_ERROR";
