//PHOTO

export const GET_PHOTO_PROGRESS = "GET_PHOTO_PROGRESS";
export const GET_PHOTO_SUCCESS = "GET_PHOTO_SUCCESS";
export const GET_PHOTO_ERROR = "GET_PHOTO_ERROR";

export const POST_PHOTO_PROGRESS = "POST_PHOTO_PROGRESS";
export const POST_PHOTO_SUCCESS = "POST_PHOTO_SUCCESS";
export const POST_PHOTO_ERROR = "POST_PHOTO_ERROR";

export const DELETE_PHOTO_PROGRESS = "DELETE_PHOTO_PROGRESS";
export const DELETE_PHOTO_SUCCESS = "DELETE_PHOTO_SUCCESS";
export const DELETE_PHOTO_ERROR = "DELETE_PHOTO_ERROR";

export const UPDATE_PHOTO_PROGRESS = "UPDATE_PHOTO_PROGRESS";
export const UPDATE_PHOTO_SUCCESS = "UPDATE_PHOTO_SUCCESS";
export const UPDATE_PHOTO_ERROR = "UPDATE_PHOTO_ERROR";