//CONTACT

export const GET_CONTACT_PROGRESS = "GET_CONTACT_PROGRESS";
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_ERROR = "GET_CONTACT_ERROR";

export const POST_CONTACT_PROGRESS = "POST_CONTACT_PROGRESS";
export const POST_CONTACT_SUCCESS = "POST_CONTACT_SUCCESS";
export const POST_CONTACT_ERROR = "POST_CONTACT_ERROR";

export const DELETE_CONTACT_PROGRESS = "DELETE_CONTACT_PROGRESS";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_ERROR = "DELETE_CONTACT_ERROR";

export const UPDATE_CONTACT_PROGRESS = "UPDATE_CONTACT_PROGRESS";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_ERROR = "UPDATE_CONTACT_ERROR";
