//PRESS

export const GET_PRESS_PROGRESS = "GET_PRESS_PROGRESS";
export const GET_PRESS_SUCCESS = "GET_PRESS_SUCCESS";
export const GET_PRESS_ERROR = "GET_PRESS_ERROR";

export const POST_PRESS_PROGRESS = "POST_PRESS_PROGRESS";
export const POST_PRESS_SUCCESS = "POST_PRESS_SUCCESS";
export const POST_PRESS_ERROR = "POST_PRESS_ERROR";

export const DELETE_PRESS_PROGRESS = "DELETE_PRESS_PROGRESS";
export const DELETE_PRESS_SUCCESS = "DELETE_PRESS_SUCCESS";
export const DELETE_PRESS_ERROR = "DELETE_PRESS_ERROR";

export const UPDATE_PRESS_PROGRESS = "UPDATE_PRESS_PROGRESS";
export const UPDATE_PRESS_SUCCESS = "UPDATE_PRESS_SUCCESS";
export const UPDATE_PRESS_ERROR = "UPDATE_PRESS_ERROR";
