//COMMENT

export const GET_COMMENT_PROGRESS = "GET_COMMENT_PROGRESS";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_ERROR = "GET_COMMENT_ERROR";

export const POST_COMMENT_PROGRESS = "POST_COMMENT_PROGRESS";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_ERROR = "POST_COMMENT_ERROR";

export const DELETE_COMMENT_PROGRESS = "DELETE_COMMENT_PROGRESS";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";

export const UPDATE_COMMENT_PROGRESS = "UPDATE_COMMENT_PROGRESS";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_ERROR = "UPDATE_COMMENT_ERROR";
