//TEAM

export const GET_TEAM_PROGRESS = "GET_TEAM_PROGRESS";
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const GET_TEAM_ERROR = "GET_TEAM_ERROR";

export const POST_TEAM_PROGRESS = "POST_TEAM_PROGRESS";
export const POST_TEAM_SUCCESS = "POST_TEAM_SUCCESS";
export const POST_TEAM_ERROR = "POST_TEAM_ERROR";

export const DELETE_TEAM_PROGRESS = "DELETE_TEAM_PROGRESS";
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";
export const DELETE_TEAM_ERROR = "DELETE_TEAM_ERROR";

export const UPDATE_TEAM_PROGRESS = "UPDATE_TEAM_PROGRESS";
export const UPDATE_TEAM_SUCCESS = "UPDATE_TEAM_SUCCESS";
export const UPDATE_TEAM_ERROR = "UPDATE_TEAM_ERROR";
